services:
  analysis-env:
    image: abolade325/rental-bike-pred:3babeb2
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
